project_name: son-of-anthon

archives:
  - id: termux
    builds:
      - termux-arm64
    format: tar.gz
    files:
      - install/termux/install.sh

  - id: darwin
    builds:
      - darwin-amd64
      - darwin-arm64
    format: tar.gz
    files:
      - install/darwin/install.sh

  - id: windows
    builds:
      - windows-amd64
    format: zip
    files:
      - install/windows/install.bat

checksum:
  name_template: 'checksums.txt'

github:
  owner: JonyBepary
  name: son-of-anthon
