version: 2

project_name: son-of-anthon

builds:
  - id: linux-amd64
    goos: [linux]
    goarch: [amd64]
    binary: son-of-anthon
    main: ./cmd/son-of-anthon

  - id: linux-arm64
    goos: [linux]
    goarch: [arm64]
    binary: son-of-anthon
    main: ./cmd/son-of-anthon

  - id: darwin-amd64
    goos: [darwin]
    goarch: [amd64]
    binary: son-of-anthon
    main: ./cmd/son-of-anthon

  - id: darwin-arm64
    goos: [darwin]
    goarch: [arm64]
    binary: son-of-anthon
    main: ./cmd/son-of-anthon

  - id: windows-amd64
    goos: [windows]
    goarch: [amd64]
    binary: son-of-anthon
    main: ./cmd/son-of-anthon

  - id: termux-arm64
    goos: [android]
    goarch: [arm64]
    binary: son-of-anthon
    main: ./cmd/son-of-anthon

archives:
  - id: termux
    ids:
      - termux-arm64
    formats:
      - tar
    files:
      - install/termux/install.sh

  - id: darwin
    ids:
      - darwin-amd64
      - darwin-arm64
    formats:
      - tar
    files:
      - install/darwin/install.sh

  - id: windows
    ids:
      - windows-amd64
    formats:
      - zip
    files:
      - install/windows/install.bat

nfpms:
  - id: linux
    ids:
      - linux-amd64
      - linux-arm64
    package_name: son-of-anthon
    vendor: Son of Anthon
    maintainer: Son of Anthon
    homepage: https://github.com/JonyBepary/son-of-anthon
    description: AI-powered multi-agent assistant
    license: MIT
    formats:
      - deb
      - rpm
    contents:
      - src: install/linux/install.sh
        dst: /usr/share/son-of-anthon/install.sh
        type: config|noreplace

checksum:
  name_template: 'checksums.txt'
