version: 2

project_name: son-of-anthon

builds:
  - id: linux-amd64
    goos: linux
    goarch: amd64
    binary: son-of-anthon

  - id: linux-arm64
    goos: linux
    goarch: arm64
    binary: son-of-anthon

  - id: darwin-amd64
    goos: darwin
    goarch: amd64
    binary: son-of-anthon

  - id: darwin-arm64
    goos: darwin
    goarch: arm64
    binary: son-of-anthon

  - id: windows-amd64
    goos: windows
    goarch: amd64
    binary: son-of-anthon

  - id: termux-arm64
    goos: android
    goarch: arm64
    binary: son-of-anthon

archives:
  - id: termux
    builds:
      - termux-arm64
    format: tar.gz
    files:
      - install/termux/install.sh

  - id: darwin
    builds:
      - darwin-amd64
      - darwin-arm64
    format: tar.gz
    files:
      - install/darwin/install.sh

  - id: windows
    builds:
      - windows-amd64
    format: zip
    files:
      - install/windows/install.bat

nfpms:
  - id: linux
    builds:
      - linux-amd64
      - linux-arm64
    package_name: son-of-anthon
    vendor: Son of Anthon
    homepage: https://github.com/JonyBepary/son-of-anthon
    description: AI-powered multi-agent assistant
    license: MIT
    formats:
      - deb
      - rpm
    contents:
      - src: son-of-anthon
        dst: /usr/bin/son-of-anthon
      - src: install/linux/install.sh
        dst: /usr/share/son-of-anthon/install.sh
        type: config|noreplace

checksum:
  name_template: 'checksums.txt'
